---
- hosts: ipa
  strategy: free 
  gather_facts: False
  tasks:
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.20 ipa.test.example.com ipa
      create: yes
  - name: Adding system1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.21 system1.test.example.com system1
      create: yes
  - name: Adding system2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.22 system2.test.example.com system1
      create: yes
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.20/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloaded Firewall. Installing Environment Packages...
    command: firewall-cmd --reload
  - name: Environment Packages Installed. Configuring IPA..
    command: yum install -y ipa-server ipa-server-dns vsftpd
#    async: 500
#    poll: 0
#    register: yum_sleeper
#  - name: --> Not actually failing.. Finishing Environment Package Installation...
#    async_status: jid={{ yum_sleeper.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    retries: 16
  - name: Configuring IPA server (Estimated Time - 7 minutes)
    command: sudo ipa-server-install --setup-dns --allow-zone-overlap --auto-reverse -a 'password' --hostname=ipa.test.example.com -r TEST.EXAMPLE.COM -p 'password' -n test.example.com -U --forwarder 8.8.8.8
    ignore_errors: yes
#    async: 1000
#    poll: 0
#    register: ipa_config_sleeper
#    ignore_errors: yes
#  - name: Still Working On IPA Configuration...It takes time ¯\_(ツ)_/¯
#    async_status: jid={{ ipa_config_sleeper.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    retries: 70   
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld