---
- hosts: system2
  become: true
  tasks:
  - name: Preparing environment
    shell: rm -rf /etc/yum.repos.d/*
  - name: Setting Up Repo
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: u=rw,g=r,o=r
  - name: Building Repo File
    blockinfile:
      path: /etc/yum.repos.d/ipa.repo
      block: |
       [ipa]
       name=ipa repo
       baseurl=http://reflector.westga.edu/repos/CentOS/7/os/x86_64/
       gpgcheck=1
       gpgkey=http://reflector.westga.edu/repos/CentOS/7/os/x86_64/RPM-GPG-KEY-CentOS-7
       enabled=1
  - name: Installing Exam Environment Packages
    yum:
      name: 
      - ipa-server
      - libselinux-python
      state: present
## These would only be needed for using the "expect" module
#      - epel-release
#  - name: Installing PIP
#    yum:
#      name: python-pip
#      state: latest
#  - name: Expect much?
#    shell: pip --upgrade pip ; pip install --ignore-installed pexpect
  - name: Disabling services
    selinux:
      state: disabled
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.5 ipa.example.com ipa
      create: yes
  - name: Adding system1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.6 system1.example.com system1
      create: yes
  - name: Adding system2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.7 system2.example.com system2
      create: yes
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Configuring network
    command: nmcli con mod "System enp0s8" ipv4.addresses "192.168.55.7/24 192.168.55.1" ipv4.dns 192.168.55.5 ipv4.dns-search example.com ipv4.method manual
  - name: Stopping NTP services
    service: name=ntpd state=stopped
  - name: Configuring IPA client
    #expect:
    command: ipa-client-install --enable-dns-updates -N --principal admin --server ipa.example.com -w password --hostname=system1.example.com --realm=EXAMPLE.COM --domain=example.com -U
    ignore_errors: yes
      #responses:
      #  (?i)user: "admin"
      #  (?i)password: "password"
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
  - name: Rebooting machine
    reboot: